### ISSUE TITLE
Bounding boxes and coordinate system indicators

### ISSUE THREAD

**Issue by kephale** [ClearVolume/scenery#10]
For 3D viewer functionality, we need something like wireframe bounding boxes with scale indicators.

Coordinate system indicators for x/y/z orientation are also needed.

**Comment by kephale** [comment]
Note that things like this exist: https://github.com/imagej/imagej-ops/blob/master/src/main/templates/net/imagej/ops/Ops.list#L119

**Comment by skalarproduktraum** [comment]
Progress tracked in #26

**Comment by skalarproduktraum** [comment]
Implemented with #26, merged to master now :)
