### ISSUE TITLE
Set and fix the center of ArcBallCameraControl

### ISSUE THREAD

**Issue by kephale** [ClearVolume/scenery#20]
It would be ideal to be able to set the focus/center of the ArcBallCameraControl, i.e. rotate about the center of an object, regardless of where the mouse is clicked on the screen.

**Comment by kephale** [comment]
This might relate to the definition of put for BehaviourMap in ui-behaviour:

> If {@code behaviour} is {@code null}, this removes the current binding for {@code key}.

but addBehaviour restricts behaviors to be non-null.

**Comment by skalarproduktraum** [comment]
ClearGLInputHandler now has a `removeBehaviour` method, see fbbd86b

**Comment by skalarproduktraum** [comment]
@kephale: This is now implemented in 0c5d7a3. Please reopen if you don't like it yet ;)
