### ISSUE TITLE
Renderer.createRenderer cannot be accessed as a static method

### ISSUE THREAD

**Issue by kephale** [ClearVolume/scenery#35]
https://github.com/ClearVolume/scenery/blob/VulkanBackend/src/main/kotlin/scenery/backends/Renderer.kt#L41

cannot be accessed as a static method, presumably because Renderer is an interface

**Comment by skalarproduktraum** [comment]
A renderer can now be created from Java with the `Renderer.Factory` companion object, e.g. via

```
Renderer.Factory.createRenderer("MyApplicationName", 1280, 720);
```
