### ISSUE TITLE
Method in HasGeometry for creating a geometry using vertex data

### ISSUE THREAD

**Issue by kephale** [ClearVolume/scenery#36]
This is for a use case where the user has a list of vertices describing triangles and wants a mesh out

https://github.com/ClearVolume/scenery/blob/VulkanBackend/src/main/kotlin/scenery/HasGeometry.kt

**Comment by skalarproduktraum** [comment]
How about using `Mesh.vertices =` (kotlin) or `Mesh.setVertices(FloatBuffer)` (java)? Or would you like to have an additional convenience method in either Mesh or HasGeometry?
