### ISSUE TITLE
Mousewheel on linux works but is slow

### ISSUE THREAD

**Issue by kephale** [ClearVolume/scenery#38]
The speed of mousewheel scroll zooming is fast enough on OSX but slow on linux

**Comment by skalarproduktraum** [comment]
@kephale: Was this particular to any of the examples? I'm asking because the default input mapping (see https://github.com/ClearVolume/scenery/blob/master/src/main/kotlin/graphics/scenery/controls/InputHandler.kt#L166 and following) doesn't define any actions for scrolling.
