### ISSUE TITLE
When closing a scenery window the process remains open

### ISSUE THREAD

**Issue by kephale** [ClearVolume/scenery#7]
If I run scenery from Eclipse and close the window, the process remains open and has to be manually closed.

**Comment by skalarproduktraum** [comment]
Are you using SceneryDefaultApplication as base or something else?

**Comment by kephale** [comment]
Aha! This hasn't been updated for SceneryDefaultApplication. I'll swap and check again.

**Comment by kephale** [comment]
For the record, it still happens when inheriting from SceneryDefaultApplication

**Comment by skalarproduktraum** [comment]
Seems to be an issue on OSX with how JOGL handles the animator thread, investigating...

**Comment by skalarproduktraum** [comment]
This is fixed with the newer renderer architecture where the renderer thread gets control (in the JOGL/OpenGL case).
